name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of Strange Toolkit does this relate to?
      options:
        - Strange Hub
        - Smart Toggle
        - Atmosphere System
        - Editor Dashboard
        - World Tab
        - Visuals Tab
        - Interactables Tab
        - Auditor Tab
        - DJ Mode Expansion
        - Game Mode Expansion
        - New Feature
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem would this feature solve? What are you trying to do?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternative approaches?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
